<project>
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.contracts</groupId>
    <artifactId>event-contracts</artifactId>
    <version>1.0.${GITHUB_RUN_NUMBER}</version>

    <properties>
        <java.version>21</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.17.0</version>
        </dependency>
    </dependencies>

    <distributionManagement>
        <repository>
            <id>github</id>
            <url>https://maven.pkg.github.com/wasana007/event-contracts</url>
        </repository>
    </distributionManagement>
</project>